- name: Fetch secrets from Azure Key Vault
  hosts: localhost
  gather_facts: no

  vars:
    secrets_file: "{{ secrets_file }}"
    vm_secrets_path: "C:\\Temp\\secrets.ini"  # Destination path on the VM

  tasks:
    - name: Debug input variables
      debug:
        msg:
          - "Secrets file: {{ secrets_file }}"
          - "VM secrets path: {{ vm_secrets_path }}"

    - name: Check if the secrets file exists
      stat:
        path: "{{ secrets_file }}"
      register: secrets_file_status

    - name: Fail if the secrets file does not exist
      fail:
        msg: "Secrets file {{ secrets_file }} does not exist"
      when: not secrets_file_status.stat.exists

    - name: Ensure the directory exists on the VM for the secrets file
      win_file:
        path: 'C:\\Temp'  # Directory on the VM where secrets will be stored
        state: directory

    - name: Upload secrets file to remote VM
      win_copy:
        src: "{{ secrets_file }}"
        dest: "{{ vm_secrets_path }}"

    - name: Clean up secrets file locally
      file:
        path: "{{ secrets_file }}"
        state: absent
